version: "3.1"
services:
  my-postgres:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - ./data:/var/lib/postgresql/data
