version: "3.3"
services:
  postgres-master:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - ./master/data:/var/lib/postgresql/data
    networks:
      mynetwork:
        ipv4_address: 172.31.0.3
  postgres-slave:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - ./slave/data:/var/lib/postgresql/data
    networks:
      mynetwork:
        ipv4_address: 172.31.0.4
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.31.0.1/24